# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TISI_NicGaj0d1CDwrmfCSYE07H3VvBm
"""

!pip install rx

import rx
from rx.subject import Subject
from rx import operators as ops
import time

# Creación de flujo de notificaciones
notificaciones = Subject()

# Definir lógica reactiva
notificaciones.pipe(
    ops.map(lambda n: f"Nueva notificación: {n}"),
).subscribe(print)

# Simulación de eventos de notificación
eventos = [
    "Juan ha completado la tarea 1",
    "Ana ha recibido una calificación en su examen",
    "Carlos ha enviado un mensaje en el foro",
    "María ha comenzado un nuevo curso"
]

for evento in eventos:
    notificaciones.on_next(evento)
    time.sleep(1)